"use client"

import { Inter } from "next/font/google";
import "./globals.css";
import TerminalHeader from "./components/Terminal/TerminalHeader";
import { SeiWalletProvider } from '@sei-js/react';

const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <SeiWalletProvider
      chainConfiguration={{
        chainId: 'atlantic-2',
        restUrl: 'https://rest.atlantic-2.seinetwork.io',
        rpcUrl: 'https://rpc.atlantic-2.seinetwork.io'
      }}
      wallets={[
        'compass',
        'fin'
      ]}
    >
      <div className={inter.className}>
        <header>
          <TerminalHeader />
        </header>
        {children}
      </div>
    </SeiWalletProvider>
  );
}
