import { Inter } from "next/font/google";
import "./globals.css";
import TerminalHeader from "./components/Terminal/TerminalHeader";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <div className={inter.className}>
      <header>
        <TerminalHeader />
      </header>
      {children}
    </div>
  );
}
